### PR TITLE
:bug: Fix build cn model

### PR DESCRIPTION
**Pull request by huchenlei**
`load_control_model` in sd-webui-controlnet script now returns a tuple of (model_net, control_model_type). This PR fixes the issue caused by this return type change.

### CODE REVIEW

**Comment by HappyBoyPat** [comment]
could I ask if you could walk me through the steps on how to implement this?  I'm not a coder/programmer type. Any help would be much appreciated. thank you!

**Comment by huchenlei** [comment]
1. Install github cli
2. checkout this PR 


When this PR is merged and you want to switch back to main branch of this extension
`git checkout master`

**Comment by huchenlei** [comment]
> do I need to run that GIT from the same folder my controlnet (or animateDiff ?) is in? Or should it find what it needs on it's own ?..and I was confused by the last line about switching back to main branch....or what a branch is in general :) Sorry...very noob'ish to this level of tech stuff. I'm an artist. Again..super big thank you for your help.

Your working directory where you execute these commands should be animatediff's repo directory. `{Your A1111 root}/extensions/sd-webui-animatediff`.

**Comment by HappyBoyPat** [comment]
Success!!! And then a failure.... :(    I got animateDiff to work with openPose, which was great...but I use IPadapters a lot as well and added one of those, and got this error, which I've never seen before..

AttributeError: 'PlugableIPAdapter' object has no attribute 'image_emb'

any pearls of wisdom ?  Thanks so much for all the help. sorry to be  a bother.

**Comment by HappyBoyPat** [comment]
thank you so much for the help.  The patch you linked me did indeed fix
openPose with AnimateDiff... I then just hit one more brick wall with
IPadapter controlnet and animateDiff..something I have never seen before.
Does this error mean anything to you ?

AttributeError: 'PlugableIPAdapter' object has no attribute 'image_emb'

I use IPadapter a ton, so if I can get this working again, along with
OpenPose...I'm golden! :)

I didn't mean to steal you as my own personal A1111 guru, but thank you
again for all your help. I really appreciate it.

cheers.

-patrick

**Comment by michaelkhboo** [comment]
i think the issue is back even with this branch after updating controlnet today.
image
 
prior to the latest controlnet update, it was still working but the use of the new IPA faceID controlnet modules will lead to 
TypeError: 'FaceIdInput' object is not subscriptable controlnet

while using the multi input function seems to lead to separate images instead of gif with the following error
 AttributeError: 'NoneType' object has no attribute 'save_infotext_txt'
 
 Is there a way to workaround this issue?

**Comment by coolgamecomic** [comment]
I have the same issue while using controlnet in Animatediff, does anyone know the reason and solution? thank you!

*** Error running process: C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1143, in process
        self.controlnet_hack(p)
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1128, in controlnet_hack
        self.controlnet_main_entry(p)
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 248, in hacked_main_entry
        model_net.reset()
    AttributeError: 'ControlModel' object has no attribute 'reset'

**Comment by HappyBoyPat** [comment]
I am of no help here...I'm just biding my time, hoping that the cavalry shows up at some point....(sobs)

**Comment by HappyBoyPat** [comment]
if it helps someone with proper knowledge, this is the error I get when trying to combine Controlnet with AnimateDiff..

*** Error running process: C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1143, in process
        self.controlnet_hack(p)
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1128, in controlnet_hack
        self.controlnet_main_entry(p)
      File "C:\AI\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 248, in hacked_main_entry
        model_net.reset()
    AttributeError: 'ControlModel' object has no attribute 'reset'

**Comment by DavideAlidosi** [comment]
> if it helps someone with proper knowledge, this is the error I get when trying to combine Controlnet with AnimateDiff..
> 
> *** Error running process: C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py Traceback (most recent call last): File "C:\AI\stable-diffusion-webui\modules\scripts.py", line 718, in process script.process(p, *script_args) File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1143, in process self.controlnet_hack(p) File "C:\AI\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1128, in controlnet_hack self.controlnet_main_entry(p) File "C:\AI\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 248, in hacked_main_entry model_net.reset() AttributeError: 'ControlModel' object has no attribute 'reset'

It's easy to fix it manually:
1) Close WebUI
2) Open the script foder of your animateDiff extension
3) Make a copy of  animatediff_cn.py
4) Replace it with this one:
[animatediff_cn.zip](https://github.com/continue-revolution/sd-webui-animatediff/files/14237557/animatediff_cn.zip)

Hope it helps!

**Comment by HappyBoyPat** [comment]
thank you! That did fix the issue with openPose not working. Don't suppose you have a fix for IP adapter no longer working with animateDiff too ?  I get this error these days...

raise AttributeError("'{}' object has no attribute '{}'".format(
    AttributeError: 'PlugableIPAdapter' object has no attribute 'image_emb'. Did you mean: 'get_image_emb'?

thanks again!

**Comment by continue-revolution** [comment]
I apologize for waiting so long. 
- I was originally planning to work on https://github.com/Mikubill/sd-webui-controlnet/pull/2352, but it was very challenging and very ugly to do magic animate
- Then I tried to do a massive rewrite of sd-webui-controlnet to let it look similar to forge, but I found the workload is very huge.

Today I will try my best to make AnimateDiff work normally in WebUI 1.8.0-RC + ControlNet main branch. I will see what I should do later on.

**Comment by MaxWhite14** [comment]
> thank you! That did fix the issue with openPose not working. Don't suppose you have a fix for IP adapter no longer working with animateDiff too ? I get this error these days...
> 
> raise AttributeError("'{}' object has no attribute '{}'".format( AttributeError: 'PlugableIPAdapter' object has no attribute 'image_emb'. Did you mean: 'get_image_emb'?
> 
> thanks again!

Did u managed to fix this problem somehow? 
Getting same error still

**Comment by HappyBoyPat** [comment]
still broken for me :(

**Pull request merged**
