### PR TITLE
Safetensors loading

### PR DESCRIPTION
**Pull request by neph1**
Safetensors loading + one for the model zoo.
If someone has a better suggestion for the device selection, let me know.

Model here:
https://huggingface.co/guoyww/animatediff/tree/refs%2Fpr%2F3

### CODE REVIEW

**Comment by continue-revolution** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/sd_models.py#L285

**Comment by continue-revolution** [comment]
Also please give me a link to the model you specify.

**Comment by continue-revolution** [comment]
I mean that you can directly import and use that function. No need to copying it.

Please post links to the safetensors models you mentioned in the model zoo.

**Comment by neph1** [comment]
I added the models to the original comment: https://huggingface.co/guoyww/animatediff/tree/refs%2Fpr%2F3

**Comment by continue-revolution** [comment]
I see. Looks good to me. Will merge shortly after I finish debugging ControlNet and infv2v.

**Pull request merged**
