### PR TITLE
1.9.3

### PR DESCRIPTION
**Pull request by continue-revolution**
See #87 for detail. Some of these refactors will be merged to master, some will be discarded. Will work on this after #89

### CODE REVIEW

**Comment by arilss** [comment]
-Add support for webp and apng file formats
-Add quality sliders and lossless options for webp and apng

I love the amazing lossless feature he created.
I think **webp is working** well

**Comment by Soulreaver90** [comment]
Just to comment and say the webp has been working amazingly well. The files are a 1/4 in size with outstanding quality.

**Comment by continue-revolution** [comment]
@zappityzap could you help me to integrate webp output format and infotext copy-past into this extension? Other parts should be discarded given the current large refactor after his PR. His commit should be in [here](https://github.com/continue-revolution/sd-webui-animatediff/pull/92/commits/e9a3f3d002d744faeeb7c7fee35c5a966b41899c).

**Comment by zappityzap** [comment]
I'll take a look.

**Pull request merged**
