### PR TITLE
Add half-percision support

### LINKED ISSUE #48: [Bug]: Apple M1 crash
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

Using 32GB M1 Max. 

Process gets to generating percentage stage and then python crashes at 0%.

Can't see mention of mac compatibility anywhere but assume it's not compatible with MPS?

### Steps to reproduce the problem

txt2Img or img2img. 
various SD1.5 models (inc default)
Euler a (and others). 
256 x 256. 
mm_sd_v14.ckpt or mm_sd_v15.ckpt, 
with / without Move motion module to CPU

### What should have happened?

Shouldn't crash.

### Commit where the problem happens

webui: 68f336b
extension: 48fc19d1

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No (default).
```

### Console logs

```Shell
2023-08-03 13:08:45,523 - AnimateDiff - INFO - AnimateDiff process start with video Max frames 16, FPS 8, duration 2.0,  motion module mm_sd_v14.ckpt.
2023-08-03 13:08:45,523 - AnimateDiff - INFO - Loading motion module mm_sd_v14.ckpt from /Users/js/stable-diffusion-webui/extensions/sd-webui-animatediff/model/mm_sd_v14.ckpt
2023-08-03 13:08:50,893 - AnimateDiff - WARNING - Missing keys <All keys matched successfully>
2023-08-03 13:08:51,316 - AnimateDiff - INFO - Hacking GroupNorm32 forward function.
2023-08-03 13:08:51,316 - AnimateDiff - INFO - Injecting motion module mm_sd_v14.ckpt into SD1.5 UNet input blocks.
2023-08-03 13:08:51,316 - AnimateDiff - INFO - Injecting motion module mm_sd_v14.ckpt into SD1.5 UNet output blocks.
2023-08-03 13:08:51,316 - AnimateDiff - INFO - Injection finished.
  0%|                                                                                                                                            | 0/25 [00:00<?, ?it/s]loc("mps_add"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/97f6331a-ba75-11ed-a4bc-863efbbaf80d/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":228:0)): error: input types 'tensor<32x1024x320xf16>' and 'tensor<320xf32>' are not broadcast compatible
LLVM ERROR: Failed to infer result type(s).
./webui.sh: line 254: 46832 Abort trap: 6           "${python_cmd}" "${LAUNCH_SCRIPT}" "$@"
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by remixer-dec**
This PR adds float16 inference support and solves #48

close #48

### CODE REVIEW

**Comment by continue-revolution** [comment]
Better to auto check if possible. Using webui no-half command line argument could help

**Comment by continue-revolution** [comment]
close #48

**Comment by continue-revolution** [comment]
alright, the floating point spec seems to have significant impact on the inference result. I'll just let users specify.

**Comment by remixer-dec** [comment]
Alright, thanks!

**Pull request merged**
